version: 0.2

phases:
  pre_build:
    commands:
      - echo "[PRE_BUILD] Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}

  build:
    commands:
      - echo "[BUILD] Building Laravel Docker image..."
      - docker build --no-cache -f Dockerfile.deployment -t ${CONTAINER_NAME} .
      - docker tag ${CONTAINER_NAME} ${REPOSITORY_URI}:latest

  post_build:
    commands:
      - echo "[POST_BUILD] Pushing image to ECR..."
      - docker push ${REPOSITORY_URI}:latest

      - echo "MIGRATION_TASK_DEFINITION=${MIGRATION_TASK_DEFINITION}"
      - echo "ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}"
      - echo "SUBNET_ID_1=${SUBNET_ID_1}"
      - echo "SUBNET_ID_2=${SUBNET_ID_2}"
      - echo "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}"

      - |
        echo "[POST_BUILD] Running Laravel migration with ${MIGRATION_TASK_DEFINITION}"
        TASK_ARN=$(aws ecs run-task \
          --cluster ${ECS_CLUSTER_NAME} \
          --launch-type FARGATE \
          --task-definition ${MIGRATION_TASK_DEFINITION} \
          --network-configuration "awsvpcConfiguration={subnets=[${SUBNET_ID_1},${SUBNET_ID_2}],securityGroups=[${SECURITY_GROUP_ID}],assignPublicIp=DISABLED}" \
          --region ap-northeast-1 \
          --query "tasks[0].taskArn" \
          --output text)

        echo "[INFO] Migration task started: $TASK_ARN"

        echo "[INFO] Waiting for task to finish..."
        aws ecs wait tasks-stopped --cluster ${ECS_CLUSTER_NAME} --tasks $TASK_ARN --region ap-northeast-1

        echo "[INFO] Waiting 10 seconds for CloudWatch logs to be available..."
        sleep 10


        echo "[INFO] Fetching CloudWatch Logs for migration task..."
        LOG_GROUP="/ecs/${PROJECT}-${ENVIRONMENT}/task/migrate"
        LOG_STREAM=$(aws logs describe-log-streams \
          --log-group-name "$LOG_GROUP" \
          --order-by LastEventTime \
          --descending \
          --max-items 1 \
          --query "logStreams[0].logStreamName" \
          --output text \
          --region ap-northeast-1)

        aws logs get-log-events \
        --log-group-name "$LOG_GROUP" \
        --log-stream-name "$LOG_STREAM" \
        --region ap-northeast-1 \
        --query "events[*].message" \
        --output text

      - echo "[POST_BUILD] Writing imagedefinitions.json for ECS Deploy..."
      - printf '[{"name":"%s","imageUri":"%s:latest"}]' "$CONTAINER_NAME" "$REPOSITORY_URI" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
