version: 0.2

phases:
  pre_build:
    commands:
      - echo "[PRE_BUILD] Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  build:
    commands:
      - echo "[BUILD] Building Laravel Docker image..."
      - docker build --no-cache -f Dockerfile.deployment -t ${CONTAINER_NAME} .
      - docker tag ${CONTAINER_NAME} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nagoyameshi-prod-ecr:latest

  post_build:
    commands:
      - echo "[POST_BUILD] Pushing image to ECR..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/nagoyameshi-prod-ecr:latest

      - echo "MIGRATION_TASK_DEFINITION=${MIGRATION_TASK_DEFINITION}"
      - echo "ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}"
      - echo "SUBNET_ID_1=${SUBNET_ID_1}"
      - echo "SUBNET_ID_2=${SUBNET_ID_2}"
      - echo "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}"

      - echo "[POST_BUILD] Running Laravel migration with ${MIGRATION_TASK_DEFINITION}"
      - |
        TASK_ARN=$(aws ecs run-task \
          --cluster ${ECS_CLUSTER_NAME} \
          --launch-type FARGATE \
          --task-definition ${MIGRATION_TASK_DEFINITION} \
          --network-configuration "awsvpcConfiguration={subnets=[${SUBNET_ID_1},${SUBNET_ID_2}],securityGroups=[${SECURITY_GROUP_ID}],assignPublicIp=DISABLED}" \
          --region ap-northeast-1 \
          --output json \
          | jq -r '.tasks[0].taskArn // empty')

        echo "[DEBUG] TASK_ARN=${TASK_ARN}"
        if [ -z "$TASK_ARN" ] || [ "$TASK_ARN" = "null" ]; then
          echo "[ERROR] Failed to start migration task. TASK_ARN is empty."
          exit 1
        fi

      - echo "[INFO] Waiting for migration task to stop..."
      - aws ecs wait tasks-stopped \
          --cluster ${ECS_CLUSTER_NAME} \
          --tasks $TASK_ARN \
          --region ap-northeast-1

      - echo "[INFO] Fetching latest log stream from CloudWatch Logs..."
      - |
        for i in {1..30}; do
          LOG_STREAM=$(aws logs describe-log-streams \
            --log-group-name "/ecs/${PROJECT}-${ENVIRONMENT}/task/migrate" \
            --order-by LastEventTime \
            --descending \
            --max-items 1 \
            --region ap-northeast-1 \
            --query "logStreams[0].logStreamName" \
            --output text)
          if [ -n "$LOG_STREAM" ] && [ "$LOG_STREAM" != "None" ]; then
            echo "[INFO] Found latest log stream: $LOG_STREAM"
            break
          fi
          echo "[INFO] Log stream not found yet. Retrying in 10 seconds... ($i/30)"
          sleep 10
        done

        if [ -z "$LOG_STREAM" ] || [ "$LOG_STREAM" = "None" ]; then
          echo "[ERROR] Could not find log stream in CloudWatch Logs."
          exit 1
        fi

      - echo "[INFO] Fetching log events from CloudWatch Logs..."
      - aws logs get-log-events \
          --log-group-name "/ecs/${PROJECT}-${ENVIRONMENT}/task/migrate" \
          --log-stream-name "$LOG_STREAM" \
          --region ap-northeast-1 \
          --query "events[*].message" \
          --output text

      - echo "[POST_BUILD] Writing imagedefinitions.json for ECS Deploy..."
      - printf '[{"name":"%s","imageUri":"%s:latest"}]' "$CONTAINER_NAME" "$REPOSITORY_URI" > imagedefinitions.json
      - ls -l imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
